- hosts: all  
  strategy: free
  tasks: 

  # According to https://github.com/rancher/k3s/issues/60#issuecomment-467858023 we need to resolve the hostname, but it doesn't seem to really cause the error
  # - name: Replace localhost by hostname
  #   become: yes
  #   args:
  #     # linefile_module is not really suiteable since we want to replace dynamically with the real hostname of our machine to keep things flexible
  #     warn: no
  #   shell: 'sed -i "s/localhost/$(hostname -f)/g" /etc/hosts'

  - name: Install k3s
    shell: "curl -sfL https://get.k3s.io | sh -"
    args:
      creates: /usr/local/bin/k3s-uninstall.sh

  - name: Wait for k3s.yml
    wait_for: 
      path: /etc/rancher/k3s/k3s.yaml

  # Per default, k3s creates its config in /etc/rancher/k3s/k3s.yaml with requires root permission. --write-kubeconfig-mode allows to customize that so that our vagrant user can access it
  - name: Modify k3s service parameter
    become: yes 
    replace:
      path: /etc/systemd/system/k3s.service
      regexp: 'server (.+)?\\'
      replace: 'server --write-kubeconfig-mode 644 \\'

  - name: Reload and restart k3s service
    become: yes
    systemd:
      name: k3s
      state: restarted
      daemon_reload: yes

  - name: Create .kube dir
    file: 
      path: ~/.kube
      state: directory

  # Required for helm
  - name: Copy kubeconfig to default kubectl dir
    become: yes
    copy: 
      src: /etc/rancher/k3s/k3s.yaml
      dest: "/home/{{ ansible_user_id }}/.kube/config"
      remote_src: yes
      owner: "{{ ansible_user_id }}"